name: Test Microceph Action

on:
  push:
  pull_request:

jobs:
  linting:
    runs-on: ubuntu-latest
    name: Linting
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Lint
        run: |
          # Check bash scripts and action.yml format
          sudo apt install -qq -y python3 python3-yaml
          shellcheck *.sh
          python3 -c "import yaml; yaml.safe_load(open('action.yml').read())"

  testing:
    runs-on: ubuntu-latest
    name: Testing
    steps:
      - name: Microceph setup
        uses: phvalguima/microceph-action@main
        with:
          osdsize: "15G"
      - name: Verify S3 is accessible
        run: |
          # Check microceph and haproxy are set
          set -eux
          sudo microceph.ceph status
          source microceph.source
          s3cmd --no-check-certificate --host "${S3_SERVER_URL}" \
                --host-bucket="${S3_SERVER_URL}/%(bucket)" \
                --access_key="${S3_ACCESS_KEY}" \
                --ca-cert="${S3_CA_BUNDLE_PATH}" \
                --secret_key="${S3_SECRET_KEY}" ls
          dd if=/dev/urandom of=testing bs=64M count=4
          INPUT="$(md5sum testing | awk '{print $1}')"
          s3cmd --no-check-certificate --host "${S3_SERVER_URL}" \
                --host-bucket="${S3_SERVER_URL}/%(bucket)" \
                --access_key="${S3_ACCESS_KEY}" \
                --ca-cert="${S3_CA_BUNDLE_PATH}" \
                --secret_key="${S3_SECRET_KEY}" \
                put testing "s3://${S3_BUCKET}"/testing
          s3cmd --no-check-certificate --host "${S3_SERVER_URL}" \
                --host-bucket="${S3_SERVER_URL}/%(bucket)" \
                --access_key="${S3_ACCESS_KEY}" \
                --ca-cert="${S3_CA_BUNDLE_PATH}" \
                --secret_key="${S3_SECRET_KEY}" \
                get "s3://${S3_BUCKET}"/testing result-testing
          if [[ "${INPUT}" != "$(md5sum result-testing | awk '{print $1}')" ]]; then
              exit 1
          fi
